### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by hsavit1** [woxtu/UIButton-WithObject#1]
on line 17,

```
    objc_msgSend(self_, action, self, [object copy]);
```

gives the error "Too many arguments on function call, expected 0, have 4"

I didnt touch the class at all

**Comment by hsavit1** [comment]
this is an error with the latest version of cocoapods, 0.36.3. Downgrade to 0.35 to fix!

**Comment by woxtu** [comment]
Thank you for your report.

The change of LLVM seems to be the cause, so I fixed it and bumped version. Please try it with the latest CocoaPods when you have time.
